### ISSUE TITLE
Can not find any crash in LAVA-M base64 in 5 hours.

### ISSUE THREAD

**Issue by liuliqaz** [puppet-meteor/MOpt-AFL#8]
Hello, I try to run the experiment in the paper and run MOpt-AFL in LAVA-M, and I run base64 in 5 hours, but I can not find any crash. Here is the instruction I ues:
`
MOpt-AFL/MOpt/afl-fuzz -m none -i fuzzer_input/ -o output4 -Q coreutils-8.24-lava-safe/lava-install/bin/base64 -d @@
`
Here is the run result:
![1](https://user-images.githubusercontent.com/56335649/116807411-ad271b80-ab65-11eb-927d-a60cb91f1e97.png)
Thanks for your help!!!

**Comment by puppet-meteor** [comment]
Hi, since the experiment only lasts 5 hours, I use  `-L 0`  in the unstruction: 
`MOpt-AFL/MOpt/afl-fuzz -m none -i fuzzer_input/ -o output4 -L 0 -Q coreutils-8.24-lava-safe/lava-install/bin/base64 -d @@`

Moreover, I use a better seed set. I use afl-cmin to filter out the input files in inputs/, then random select several files as the initial seed set.

**Comment by liuliqaz** [comment]
Thank you so much!!! I will try again. By the way, I try to use this method in my project. Maybe I can ask you some questions by qq, Here is my qq number: 2523008742. Thanks for your help again!!!
